config/routes.rb
Rails.application.routes.draw do
  root "artworks#index"

  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }

  get 'pages/about'

  resources :artworks do
    resources :comments, only: [:create]
    member do
      get :get_comments
    end
  end

  namespace :admin do
    get 'dashboard/index'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin
      can :manage, :dashboard

    end
    can :manage, User if user.supervisor_role?
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_one_attached :featured_img do |attachable|
    attachable.variant :thumb, resize: "100x100"
  end

  # dependent: :destroy means the comments related
  # to the specific post in mention get deleted if the post does.
  has_many :comments, dependent: :destroy

  validates :city, presence: true
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  # featured_img: nil,
  # neighbourhood:
  # artist:
  # copyright_img:
  # materials:
  # source_id:
  # date_placement:
  # date_bought:
  # copyright_description:
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :artwork
  belongs_to :user

  def self.by_created_at
    order("created_at DESC")
  end
end

app/models/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :role])
  end
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do 
    def public_count
      where(status: 'public').count
    end
  end 
  
  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Gravtastic
  gravtastic

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  validates :display_name, :email, presence: true
  validates :email, uniqueness: true

  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, confirmation: true

  has_many :comments
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
    if params[:approved] == "false"
      @users = User.where(approved: false)
    else
      @users = User.all
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: [:show, :edit, :update, :show, :get_comments]
  # Guest users can only view artworks
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @artworks = Artwork.paginate(page: params[:page], per_page: 50)
  end

  def show
  end

  def new
    @artwork = Artwork.new
  end

  def create
    @artwork = Artwork.new(artwork_params)

    if @artwork.save
      redirect_to @artwork, notice: "Blog was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @artwork.update(artwork_params)
      redirect_to @artwork
    else
      render :edit
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork.destroy

    redirect_to root_path, notice: "Artwork was successfully destroyed"
  end

  private

  def artwork_params
    params.require(:artwork).permit(:title, :description)
  end

  def set_artwork
    @artwork = Artwork.find(params[:id])
  end

  def get_comments
    comments = @artwork.comments.select("comments.*", users.display_name).joins(":user").by_created_at
    render json: {comments: comments }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_artwork
  before_action :set_comment, only: [:destroy]

  def create
    @comment = @artwork.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.artwork_id = params[:artwork_id]
    @comment.save

    redirect_to artwork_path(@artwork)

  end

  def destroy
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

    def set_artwork
      @artwork = Artwork.find(params[:artwork_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:display_name, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:display_name, :role])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>

<table>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %>
      <td><%= link_to "Edit", edit_user_path(user) %>
    </tr>
  <% end %>
</table>

app/views/artworks/_form.html.erb
<%= form_with model: @artwork do |form| %>
  <div class="field">
    <%= form.label :title, :class => "label" %>
    <div class="control">
      <%= form.text_field :title, :class => "input" %>
    </div>
    <% @artwork.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div class="field">
    <%= form.label :description, :class => "label" %>
    <div class="control">
      <%= form.text_field :description, :class => "input" %>
    </div>
    <% @artwork.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :status, :class => "label" %>
    <div class="control">
      <div class="select">
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
      </div>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
    <%= form.submit :class => "button is-link" %>
    </div>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<h1>Edit artwork</h1>

<%= render "form", artwork: @artwork %>

app/views/artworks/index.html.erb
<section class="pt-8 text-center">
  <div class="container mx-auto px-2">
    <h1 class="text-xl mb-8">Kunst Openbare Ruimte</h1>
    <h2 class="font-light max-w-xl m-auto">
      Het <strong>register</strong> van kunstwerken in de openbare ruimte objecten in Nederland.
    </h2>
  </div>
</section>

<section class="py-16">
  <div class="grid grid-cols-2 auto-rows-fr sm:grid-cols-3 3 md:grid-cols-5 xl:grid-cols-8">

    <% @artworks.each do |artwork| %>
      <div class="group overflow-hidden items-center justify-center flex">
        <a href="/artworks/<%= artwork.id %>" class="relative w-full h-full bg-yellow-100">
          <% if artwork.featured_img.attached? %>
            <div>
              <%= image_tag artwork.featured_img.variant(:gravity=>"center", resize: "400x400^", crop: '400x400+0+0').processed, alt: artwork.title, class:'w-full' %>
            </div>
          <% end %>
          <div class="transition-opacity duration-300 absolute top-0 left-0 right-0 bottom-0 opacity-0 group-hover:opacity-100 text-center bg-white w-full bg-opacity-50 text-center flex flex-col justify-center items-center p-4">
            <h3 class="font-bold text-xl"><%= artwork.title.truncate(40) %></h3>
            <div class="text-sm"><%= artwork.artist %></div>
            <div class="text-xs bg-gray-800 text-white rounded px-2 py-1 mt-2"><%= artwork.comments.count %> comments</div>
          </div>
        </a>
      </div>
    <% end %>
  </div>

  <div class="text-center my-4 pagination">
    <%= will_paginate @artworks %>
  </div>
</section>

app/views/artworks/new.html.erb
<h1 class="is-size-1">Nieuw kunstwerk toevoegen</h1>

<%= render "form", artwork: @artwork %>

app/views/artworks/show.html.erb
<section class="py-16">
  <div class="container p-4">
    <header>
      <a href="/" class="mb-4 block text-xs tracking-wider uppercase hover:underline">
        &larr; Naar het overzicht
      </a>

      <h1 class="font-bold text-3xl my-4"><%= @artwork.title %></h1>

      <% if @artwork.featured_img.attached? %>
        <div class="mb-2">
          <%= image_tag @artwork.featured_img.variant(:gravity=>"center", resize: "1600x800^", crop: '1600x800+0+0').processed, alt: @artwork.title %>
        </div>
      <% end %>

      <p class="text-sm text-gray-600 mb-4 uppercase">
        <%= @artwork.city %> // <%= @artwork.neighbourhood %>
      </p>
    </header>
    <div class="md:flex">
      <div class="md:w-3/4 md:pr-4 leading-relaxed">
        <div><%= @artwork.description %></div>
        <div class="text-sm my-8 text-gray-400">
          <hr class="mb-4" />
          <% if @artwork.copyright_description %>
            <p>
              &copy; Beschrijving: <%= @artwork.copyright_description %>
            </p>
          <% end %>
          <% if @artwork.copyright_img %>
            <p>
              &copy; Foto: <%= @artwork.copyright_img %>
            </p>
          <% end %>
        </div>

        <div class="comments">
            <h2 class="subtitle is-5"><strong><%= @artwork.comments.count %></strong> Reacties</h2>
            <%= render @artwork.comments %>
            <div class="comment-form">
              <%= render 'comments/form' %>
            </div>
          </div>
      </div>
      <div class="md:w-1/4 md:pl-4 text-sm leading-loose">
        <dl>
          <dt class="font-bold">Kunstenaar</dt>
          <dd><%= @artwork.artist || onbekend %></dd>
          <dt class="font-bold">Materialen</dt>
          <dd>

            <%= @artwork.materials || "Onbekend" %>
          </dd>
          <dt class="font-bold">Volgnummer</dt>
          <dd><%= @artwork.source_id %></dd>
          <dt class="font-bold">Plaatsingsdatum</dt>
          <dd>
            <% if (@artwork.date_placement) %>
              <%= @artwork.date_placement.strftime("%m-%d-%Y")  %>
            <% else %>
              Onbekend
            <% end %>
          </dd>
          <dt class="font-bold">Datum aanschaf</dt>
          <dd>
          <% if @artwork.date_bought %>
            <%= @artwork.date_bought.strftime("%m-%d-%Y") %>
          <% else %>
            Onbekend
          <% end %></dd>
          <dt class="font-bold">Bron</dt>
          <dd>
            <a
              href="https://denhaag.dataplatform.nl/#/home"
              target="_blank"
            >
              Gemeente Den Haag
            </a>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</section>

app/views/comments/_comment.html.erb
<div class="flex-1 border rounded-lg px-4 py-2 sm:px-6 sm:py-4 leading-relaxed bg-gray-100 mb-4">
  <div class="flex items-center">
    <%= image_tag comment.user.gravatar_url, :class => "h-4 rounded-full mr-2" %>
    <strong><%= comment.user.display_name %></strong>
  </div>
  <span class="text-xs text-gray-400"><%= comment.created_at.strftime("%m-%d-%Y %H:%m") %></span>
  <p class="text-sm"><%= comment.body %></p>
</div>

app/views/comments/_form.html.erb
<% if current_user %>
  <%= form_with model: [ @artwork, @artwork.comments.build ] do |form| %>
    <h3 class="subtitle is-3">Wat vind jij van dit kunstwerk?</h3>
    <div class="w-full md:w-full mb-2 mt-2">
      <%= form.text_area :body, :rows => 5, :placeholder => "Jouw reactie", :class => "bg-gray-100 rounded border border-gray-400 leading-normal resize-none w-full h-20 py-2 px-3 font-medium placeholder-gray-700 focus:outline-none focus:bg-white" %>
    </div>
    <div class="w-full md:w-full flex items-start md:w-full">
      <div class="flex items-start w-1/2 text-gray-700 px-2 mr-auto"></div>
      <div class="-mr-1">
        <%= form.submit "Commentaar plaatsen", :class => "bg-white text-gray-700 font-medium py-1 px-4 border border-gray-400 rounded-lg tracking-wide mr-1 hover:bg-gray-100" %>
      </div>
    </div>
  <% end %>
<% else %>
  <%= link_to "Wat vind jij hiervan? Login om een commentaar te plaatsen", new_user_session_path, :class => "text-sm leading-none text-black" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="nl">
  <head>
    <title>Kunst Openbare Ruimte</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Deze kaart toont kunstwerken in de openbare ruimte objecten in Den Haag.">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="flex flex-col min-h-screen">
    <%= render "shared/header" %>

    <% unless flash.empty? %>
      <script type="text/javascript">
          <% flash.each do |f| %>
        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
        toastr['<%= type %>']('<%= f[1] %>');
      <% end %>
      </script>
    <% end %>


    <main class="flex-1">
      <%= yield %>
    </main>

    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="py-4 bg-black text-white">
  <div class="container m-auto text-sm italic text-center opacity-50">
    © 2021
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-teal p-6" data-controller="toggle">
  <div class="flex items-center flex-no-shrink text-black mr-6">
    <a href="/" alt="home"><span class="font-semibold text-xl tracking-tight">Kunst Openbare Ruimte</span></a>
  </div>
  <div class="block lg:hidden">
    <button data-action="click->toggle#toggle" class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
      <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>

  <div data-toggle-target="element" class="hidden w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <a href="/" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter mr-4">
        Lijst
      </a>
    </div>
    <div>
      <% if user_signed_in? %>
        <%= link_to current_user.email, edit_user_registration_path, :class => "inline-block text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent hover:text-white hover:bg-black hover:no-underline mt-4 lg:mt-0" %>
        <%= link_to "Uitloggen", destroy_user_session_path, method: :delete, :class => "inline-block text-sm px-4 py-2 leading-none text-black hover:border-transparent hover:text-white hover:bg-black hover:no-underline mt-4 lg:mt-0"%>
      <% else %>
        <%= link_to "Login", new_user_session_path, :class => "inline-block text-sm px-4 py-2 leading-none border rounded text-black border-black hover:border-transparent hover:text-white hover:bg-black hover:no-underline mt-4 lg:mt-0" %>
      <% end %>
    </div>
  </div>
</nav>